domain: soundslocal.co.uk
budgie_plugins:
  - budgie.contrib.markdown
  - budgie.contrib.staticfiles
  - budgie.contrib.icons
  - budgie.contrib.sections
  - budgie.contrib.grids
  - budgie.contrib.bento
  - budgie.contrib.accordion
  - budgie.contrib.cta
  - budgie.contrib.oembed
  - budgie.contrib.calendly

frontend_packages:
  - aos
  - bootstrap
  - bootstrap-icons
  - imagesloaded

blog_heading: This is the blog
blog_description: No-one reads digital agencies' blog posts, but we insist on writing them regardless.

menus:
  main:
    - path: /
      text: Home
    - path: /services/
      text: Services
    - path: /projects/
      text: Projects
    - path: /blog/
      text: Blog
