domain: soundslocal.co.uk
budgie_plugins:
  - budgie.contrib.markdown
  - budgie.contrib.staticfiles
  - budgie.contrib.icons
  - budgie.contrib.sections
  - budgie.contrib.grids
  - budgie.contrib.bento
  - budgie.contrib.carousel
  - budgie.contrib.cta
  - budgie.contrib.oembed
  - budgie.contrib.calendly

frontend_packages:
  - aos
  - bootstrap
  - bootstrap-icons
  - imagesloaded

menus:
  main:
    - path: /
      text: Home
